[package]
name = "parse-cryo-erc20-xfer-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "2.0"
ethers-core = "2.0.9"
