use std::env;      
// use ethers::prelude::*;                                                                                                                                                                                                                                                                                                                                                  
use ethers::types::U256;      
use ethers::utils::hex::decode;
                                                                                                                                                                                                                                                                                                                                                                      
fn main() {                                                                                                                                                                                                                                                                                                                                                          
    let args: Vec<String> = env::args().collect();                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                     
    if args.len() > 1 {                                                                                                                                                                                                                                                                                                                                              
    // if args.len() > 2 {                                                                                                                                                                                                                                                                                                                                              
        let input = &args[1];                                                                                                                                                                                                                                                                                                                                        
        let base: u32 = 10;                                                                                                                                                                                                                                                                                                                                       
        let variables: Vec<&str> = input.split(',').collect();                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                     
        if variables.len() == 14 {                                                                                                                                                                                                                                                                                                                                   
            let (block_number, transaction_index, transaction_hash, nonce, from_address, to_address, value, input, gas_limit, gas_price, transaction_type, max_priority_fee_per_gas, max_fee_per_gas, chain_id) =                                                                                                                                                    
                (                                                                                                                                                                                                                                                                                                                                                    
                    variables[0], variables[1], variables[2], variables[3], variables[4], variables[5],                                                                                                                                                                                                                                                              
                    variables[6], variables[7], variables[8], variables[9], variables[10], variables[11],                                                                                                                                                                                                                                                            
                    variables[12], variables[13],                                                                                                                                                                                                                                                                                                                    
                );                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                     
            let instruction = &input[2..10];                                                                                                                                                                                                                                                                                                                         
            let receiver = format!("0x{}", &input[34..74]);                                                                                                                                                                                                                                                                                                          
            let bytes = decode(&input[74..]).unwrap();
            let amount = U256::from(bytes.as_slice());
                                                                                                                                                                                                                                                                                                                                         
            println!("{},{},{},{},{},{}", block_number, transaction_hash, from_address, receiver, amount, to_address);
        } else {                                                                                                                                                                                                                                                                                                                                                     
            println!("Invalid number of variables provided.");                                                                                                                                                                                                                                                                                                       
        }                                                                                                                                                                                                                                                                                                                                                            
    } else {                                                                                                                                                                                                                                                                                                                                                         
        println!("No input entered.");                                                                                                                                                                                                                                                                                                                               
    }                                                                                                                                                                                                                                                                                                                                                                
}